name: ${WATCH_COMPOSE_PROJECT_NAME}

services:
  # Prometheus - Metrics Collection & Storage
  prometheus:
    image: ${WATCH_PROMETHEUS_IMAGE:-prom/prometheus:latest}
    container_name: ${WATCH_COMPOSE_PROJECT_NAME}_prometheus
    restart: unless-stopped
    user: root
    environment:
      TZ: ${TIMEZONE:-Europe/Amsterdam}
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=${WATCH_PROMETHEUS_RETENTION:-30d}'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - kompose_network
    ports:
      - "${WATCH_PROMETHEUS_PORT:-9090}:9090"
    labels:
      # Traefik enabled/disabled per service
      - 'traefik.enable=${TRAEFIK_ENABLED_WATCH_PROMETHEUS:-false}'
      
      # HTTP to HTTPS redirect (only for production when PROTOCOL=https)
      - 'traefik.http.middlewares.${WATCH_COMPOSE_PROJECT_NAME}-prometheus-redirect-web-secure.redirectscheme.scheme=${PROTOCOL}'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-prometheus-web.middlewares=${WATCH_COMPOSE_PROJECT_NAME}-prometheus-redirect-web-secure'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-prometheus-web.rule=Host(`${SUBDOMAIN_WATCH_PROMETHEUS}${ROOT_DOMAIN:+.${ROOT_DOMAIN}}`)'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-prometheus-web.entrypoints=web'
      
      # Secure configuration (HTTPS in production, HTTP in local)
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-prometheus-web-secure.rule=Host(`${SUBDOMAIN_WATCH_PROMETHEUS}${ROOT_DOMAIN:+.${ROOT_DOMAIN}}`)'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-prometheus-web-secure.tls.certresolver=${PROTOCOL:+resolver}'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-prometheus-web-secure.tls=${PROTOCOL:+true}'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-prometheus-web-secure.entrypoints=web-secure'
      
      # Middlewares
      - 'traefik.http.middlewares.${WATCH_COMPOSE_PROJECT_NAME}-prometheus-web-secure-compress.compress=true'
      - 'traefik.http.middlewares.${WATCH_COMPOSE_PROJECT_NAME}-prometheus-auth.basicauth.users=${WATCH_PROMETHEUS_AUTH}'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-prometheus-web-secure.middlewares=${WATCH_COMPOSE_PROJECT_NAME}-prometheus-web-secure-compress,${WATCH_COMPOSE_PROJECT_NAME}-prometheus-auth'
      
      # Load balancer configuration
      - 'traefik.http.services.${WATCH_COMPOSE_PROJECT_NAME}-prometheus-web-secure.loadbalancer.server.port=9090'
      - 'traefik.docker.network=${NETWORK_NAME:-kompose}'

  # Grafana - Metrics Visualization
  grafana:
    image: ${WATCH_GRAFANA_IMAGE:-grafana/grafana:latest}
    container_name: ${WATCH_COMPOSE_PROJECT_NAME}_grafana
    restart: unless-stopped
    user: root
    environment:
      TZ: ${TIMEZONE:-Europe/Amsterdam}
      GF_SECURITY_ADMIN_USER: ${WATCH_GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${WATCH_GRAFANA_ADMIN_PASSWORD}
      GF_INSTALL_PLUGINS: ${WATCH_GRAFANA_PLUGINS:-grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,grafana-worldmap-panel}
      GF_USERS_ALLOW_SIGN_UP: false
      GF_SERVER_ROOT_URL: https://${TRAEFIK_HOST_GRAFANA}
      GF_DATABASE_TYPE: postgres
      GF_DATABASE_HOST: ${CORE_DB_HOST}:${CORE_DB_PORT}
      GF_DATABASE_NAME: ${WATCH_GRAFANA_DB_NAME:-grafana}
      GF_DATABASE_USER: ${WATCH_GRAFANA_DB_USER:-grafana}
      GF_DATABASE_PASSWORD: ${WATCH_GRAFANA_DB_PASSWORD}
      GF_DATABASE_SSL_MODE: disable
      GF_ANALYTICS_REPORTING_ENABLED: false
      GF_ANALYTICS_CHECK_FOR_UPDATES: true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - kompose_network
    ports:
      - "${WATCH_GRAFANA_PORT:-3010}:3000"
    depends_on:
      prometheus:
        condition: service_healthy
    labels:
      # Traefik enabled/disabled per service
      - 'traefik.enable=${TRAEFIK_ENABLED_WATCH_GRAFANA:-false}'
      
      # HTTP to HTTPS redirect (only for production when PROTOCOL=https)
      - 'traefik.http.middlewares.${WATCH_COMPOSE_PROJECT_NAME}-grafana-redirect-web-secure.redirectscheme.scheme=${PROTOCOL}'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-grafana-web.middlewares=${WATCH_COMPOSE_PROJECT_NAME}-grafana-redirect-web-secure'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-grafana-web.rule=Host(`${SUBDOMAIN_WATCH_GRAFANA}${ROOT_DOMAIN:+.${ROOT_DOMAIN}}`)'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-grafana-web.entrypoints=web'
      
      # Secure configuration (HTTPS in production, HTTP in local)
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-grafana-web-secure.rule=Host(`${SUBDOMAIN_WATCH_GRAFANA}${ROOT_DOMAIN:+.${ROOT_DOMAIN}}`)'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-grafana-web-secure.tls.certresolver=${PROTOCOL:+resolver}'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-grafana-web-secure.tls=${PROTOCOL:+true}'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-grafana-web-secure.entrypoints=web-secure'
      
      # Middlewares
      - 'traefik.http.middlewares.${WATCH_COMPOSE_PROJECT_NAME}-grafana-web-secure-compress.compress=true'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-grafana-web-secure.middlewares=${WATCH_COMPOSE_PROJECT_NAME}-grafana-web-secure-compress'
      
      # Load balancer configuration
      - 'traefik.http.services.${WATCH_COMPOSE_PROJECT_NAME}-grafana-web-secure.loadbalancer.server.port=3000'
      - 'traefik.docker.network=${NETWORK_NAME:-kompose}'

  # OpenTelemetry Collector - Telemetry Pipeline
  otel-collector:
    image: ${WATCH_OTEL_IMAGE:-otel/opentelemetry-collector-contrib:latest}
    container_name: ${WATCH_COMPOSE_PROJECT_NAME}_otel
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE:-Europe/Amsterdam}
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector/config.yaml:/etc/otel-collector-config.yaml:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:13133/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - kompose_network
    ports:
      - "${WATCH_OTEL_GRPC_PORT:-4317}:4317"   # OTLP gRPC receiver
      - "${WATCH_OTEL_HTTP_PORT:-4318}:4318"   # OTLP HTTP receiver
      - "${WATCH_OTEL_HEALTH_PORT:-13133}:13133" # Health check
      - "${WATCH_OTEL_ZPAGES_PORT:-55679}:55679" # zPages extension
    depends_on:
      prometheus:
        condition: service_healthy

  # PostgreSQL Exporter - Core Database Metrics
  postgres-exporter:
    image: ${WATCH_POSTGRES_EXPORTER_IMAGE:-prometheuscommunity/postgres-exporter:latest}
    container_name: ${WATCH_COMPOSE_PROJECT_NAME}_postgres_exporter
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE:-Europe/Amsterdam}
      DATA_SOURCE_NAME: postgresql://${WATCH_POSTGRES_EXPORTER_USER:-kompose}:${WATCH_POSTGRES_EXPORTER_PASSWORD}@${CORE_DB_HOST}:${CORE_DB_PORT}/${WATCH_POSTGRES_EXPORTER_DB:-kompose}?sslmode=disable
      PG_EXPORTER_EXTEND_QUERY_PATH: /etc/postgres_exporter/queries.yaml
    volumes:
      - ./postgres-exporter/queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9187/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - kompose_network
    ports:
      - "${WATCH_POSTGRES_EXPORTER_PORT:-9187}:9187"

  # Redis Exporter - Core Cache Metrics
  redis-exporter:
    image: ${WATCH_REDIS_EXPORTER_IMAGE:-oliver006/redis_exporter:latest}
    container_name: ${WATCH_COMPOSE_PROJECT_NAME}_redis_exporter
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE:-Europe/Amsterdam}
      REDIS_ADDR: redis://${CORE_REDIS_HOST}:${CORE_REDIS_PORT}
      REDIS_PASSWORD: ${WATCH_REDIS_EXPORTER_PASSWORD}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9121/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - kompose_network
    ports:
      - "${WATCH_REDIS_EXPORTER_PORT:-9121}:9121"

  # MQTT Exporter - Core MQTT Broker Metrics
  mqtt-exporter:
    image: ${WATCH_MQTT_EXPORTER_IMAGE:-kpetrem/mqtt-exporter:latest}
    container_name: ${WATCH_COMPOSE_PROJECT_NAME}_mqtt_exporter
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE:-Europe/Amsterdam}
      MQTT_ADDRESS: core_mqtt
      MQTT_PORT: ${CORE_MQTT_PORT}
      MQTT_TOPIC: ${WATCH_MQTT_EXPORTER_TOPIC:-#}
      MQTT_V5_PROTOCOL: ${WATCH_MQTT_V5_PROTOCOL:-False}
      PROMETHEUS_PORT: 9000
      PROMETHEUS_PREFIX: mqtt_
      TOPIC_LABEL: topic
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9000/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - kompose_network
    ports:
      - "${WATCH_MQTT_EXPORTER_PORT:-9000}:9000"

  # cAdvisor - Container Metrics
  cadvisor:
    image: ${WATCH_CADVISOR_IMAGE:-gcr.io/cadvisor/cadvisor:latest}
    container_name: ${WATCH_COMPOSE_PROJECT_NAME}_cadvisor
    restart: unless-stopped
    privileged: true
    environment:
      TZ: ${TIMEZONE:-Europe/Amsterdam}
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - kompose_network
    ports:
      - "${WATCH_CADVISOR_PORT:-8082}:8080"

  # Node Exporter - Host System Metrics
  node-exporter:
    image: ${WATCH_NODE_EXPORTER_IMAGE:-prom/node-exporter:latest}
    container_name: ${WATCH_COMPOSE_PROJECT_NAME}_node_exporter
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE:-Europe/Amsterdam}
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9100/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    network_mode: host

  # Blackbox Exporter - Endpoint Monitoring
  blackbox-exporter:
    image: ${WATCH_BLACKBOX_EXPORTER_IMAGE:-prom/blackbox-exporter:latest}
    container_name: ${WATCH_COMPOSE_PROJECT_NAME}_blackbox_exporter
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE:-Europe/Amsterdam}
    command:
      - '--config.file=/config/blackbox.yml'
    volumes:
      - ./blackbox-exporter/blackbox.yml:/config/blackbox.yml:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9115/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - kompose_network
    ports:
      - "${WATCH_BLACKBOX_EXPORTER_PORT:-9115}:9115"

  # Loki - Log Aggregation
  loki:
    image: ${WATCH_LOKI_IMAGE:-grafana/loki:latest}
    container_name: ${WATCH_COMPOSE_PROJECT_NAME}_loki
    restart: unless-stopped
    user: root
    environment:
      TZ: ${TIMEZONE:-Europe/Amsterdam}
    command:
      - '-config.file=/etc/loki/loki-config.yaml'
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki_data:/loki
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - kompose_network
    ports:
      - "${WATCH_LOKI_PORT:-3100}:3100"
    labels:
      # Traefik enabled/disabled per service
      - 'traefik.enable=${TRAEFIK_ENABLED_WATCH_LOKI:-false}'
      
      # HTTP to HTTPS redirect (only for production when PROTOCOL=https)
      - 'traefik.http.middlewares.${WATCH_COMPOSE_PROJECT_NAME}-loki-redirect-web-secure.redirectscheme.scheme=${PROTOCOL}'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-loki-web.middlewares=${WATCH_COMPOSE_PROJECT_NAME}-loki-redirect-web-secure'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-loki-web.rule=Host(`${SUBDOMAIN_WATCH_LOKI}${ROOT_DOMAIN:+.${ROOT_DOMAIN}}`)'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-loki-web.entrypoints=web'
      
      # Secure configuration (HTTPS in production, HTTP in local)
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-loki-web-secure.rule=Host(`${SUBDOMAIN_WATCH_LOKI}${ROOT_DOMAIN:+.${ROOT_DOMAIN}}`)'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-loki-web-secure.tls.certresolver=${PROTOCOL:+resolver}'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-loki-web-secure.tls=${PROTOCOL:+true}'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-loki-web-secure.entrypoints=web-secure'
      
      # Middlewares
      - 'traefik.http.middlewares.${WATCH_COMPOSE_PROJECT_NAME}-loki-web-secure-compress.compress=true'
      - 'traefik.http.middlewares.${WATCH_COMPOSE_PROJECT_NAME}-loki-auth.basicauth.users=${WATCH_LOKI_AUTH}'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-loki-web-secure.middlewares=${WATCH_COMPOSE_PROJECT_NAME}-loki-web-secure-compress,${WATCH_COMPOSE_PROJECT_NAME}-loki-auth'
      
      # Load balancer configuration
      - 'traefik.http.services.${WATCH_COMPOSE_PROJECT_NAME}-loki-web-secure.loadbalancer.server.port=3100'
      - 'traefik.docker.network=${NETWORK_NAME:-kompose}'

  # Promtail - Log Collector
  promtail:
    image: ${WATCH_PROMTAIL_IMAGE:-grafana/promtail:latest}
    container_name: ${WATCH_COMPOSE_PROJECT_NAME}_promtail
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE:-Europe/Amsterdam}
    command:
      - '-config.file=/etc/promtail/promtail-config.yaml'
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
      - /var/log:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9080/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - kompose_network
    ports:
      - "${WATCH_PROMTAIL_PORT:-9080}:9080"
    depends_on:
      loki:
        condition: service_healthy

  # Alertmanager - Alert Management
  alertmanager:
    image: ${WATCH_ALERTMANAGER_IMAGE:-prom/alertmanager:latest}
    container_name: ${WATCH_COMPOSE_PROJECT_NAME}_alertmanager
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE:-Europe/Amsterdam}
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - ./alertmanager:/etc/alertmanager
      - alertmanager_data:/alertmanager
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9093/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - kompose_network
    ports:
      - "${WATCH_ALERTMANAGER_PORT:-9093}:9093"
    labels:
      # Traefik enabled/disabled per service
      - 'traefik.enable=${TRAEFIK_ENABLED_WATCH_ALERTMANAGER:-false}'
      
      # HTTP to HTTPS redirect (only for production when PROTOCOL=https)
      - 'traefik.http.middlewares.${WATCH_COMPOSE_PROJECT_NAME}-alertmanager-redirect-web-secure.redirectscheme.scheme=${PROTOCOL}'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-alertmanager-web.middlewares=${WATCH_COMPOSE_PROJECT_NAME}-alertmanager-redirect-web-secure'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-alertmanager-web.rule=Host(`${SUBDOMAIN_WATCH_ALERTMANAGER}${ROOT_DOMAIN:+.${ROOT_DOMAIN}}`)'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-alertmanager-web.entrypoints=web'
      
      # Secure configuration (HTTPS in production, HTTP in local)
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-alertmanager-web-secure.rule=Host(`${SUBDOMAIN_WATCH_ALERTMANAGER}${ROOT_DOMAIN:+.${ROOT_DOMAIN}}`)'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-alertmanager-web-secure.tls.certresolver=${PROTOCOL:+resolver}'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-alertmanager-web-secure.tls=${PROTOCOL:+true}'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-alertmanager-web-secure.entrypoints=web-secure'
      
      # Middlewares
      - 'traefik.http.middlewares.${WATCH_COMPOSE_PROJECT_NAME}-alertmanager-web-secure-compress.compress=true'
      - 'traefik.http.middlewares.${WATCH_COMPOSE_PROJECT_NAME}-alertmanager-auth.basicauth.users=${WATCH_ALERTMANAGER_AUTH}'
      - 'traefik.http.routers.${WATCH_COMPOSE_PROJECT_NAME}-alertmanager-web-secure.middlewares=${WATCH_COMPOSE_PROJECT_NAME}-alertmanager-web-secure-compress,${WATCH_COMPOSE_PROJECT_NAME}-alertmanager-auth'
      
      # Load balancer configuration
      - 'traefik.http.services.${WATCH_COMPOSE_PROJECT_NAME}-alertmanager-web-secure.loadbalancer.server.port=9093'
      - 'traefik.docker.network=${NETWORK_NAME:-kompose}'

volumes:
  prometheus_data:
    name: ${WATCH_COMPOSE_PROJECT_NAME}_prometheus_data
  grafana_data:
    name: ${WATCH_COMPOSE_PROJECT_NAME}_grafana_data
  alertmanager_data:
    name: ${WATCH_COMPOSE_PROJECT_NAME}_alertmanager_data
  loki_data:
    name: ${WATCH_COMPOSE_PROJECT_NAME}_loki_data

networks:
  kompose_network:
    name: ${NETWORK_NAME:-kompose}
    external: true
