name: Sync Repository Kompose via git

on:
  workflow_dispatch: # Allows workflow to be run manually
  push:
    branches:
    - main # Or your default branch
    paths:
    - 'Projects/kompose/**'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '#bot-message:') }}
    steps:
    - uses: actions/checkout@v4
      with:
        path: home
    - uses: actions/checkout@v4
      with:
        repository: valknar/kompose
        ref: main
        path: kompose
    - name: Commit and push changes (if any)
      shell: bash
      env:
        CI_COMMIT_MESSAGE: "${{ replace(github.event.head_commit.message, '#bot-message:') }}"
        CI_COMMIT_AUTHOR: technitz[bot]@valknar/kompose
        CI_COMMIT_EMAIL: admin@pivoine.art
      run: |
        cd kompose
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"

        ${{ github.workspace }}/home/.init/bin/mirror_project.sh '${{ github.event.head_commit.message }}' ../home  
