name: Sync Repository Kompose via git

on:
  workflow_dispatch: # Allows workflow to be run manually
  push:
    tags:
    - bot-merge
    paths:
    - 'Projects/kompose/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        path: home
    - uses: actions/checkout@v4
      with:
        repository: valknar/kompose
        ref: main
        path: kompose
    - name: Commit and push changes (if any)
      shell: bash
      env:
        CI_COMMIT_MESSAGE: "${{ github.event.head_commit.message }}"
        CI_COMMIT_AUTHOR: technitz[bot]@valknar/kompose
        CI_COMMIT_EMAIL: admin@pivoine.art
      run: |
        cd kompose
        git config user.name "${{ vars.CI_COMMIT_AUTHOR }}"
        git config user.email "${{ vars.CI_COMMIT_EMAIL }}"

        ${{ github.workspace }}/home/.init/bin/mirror_project.sh "${{ vars.CI_COMMIT_MESSAGE }}" ../home  
