---
# Developer Resources
- Developer:
    - GitHub:
        - icon: github.png
          href: https://github.com
          description: Code repository

    - Documentation:
        - icon: si-readthedocs.svg
          href: https://docs.kompose.sh
          description: Kompose documentation

# Tools
- Tools:
    - Docker Hub:
        - icon: docker.png
          href: https://hub.docker.com
          description: Container registry

    - Traefik Docs:
        - icon: traefik.png
          href: https://doc.traefik.io/traefik/
          description: Traefik documentation
