---
title: Kompose Dashboard
description: Centralized dashboard for all kompose.sh services
theme: dark
color: slate

# Layout configuration
layout:
  - Infrastructure:
      style: row
      columns: 3
  - Authentication:
      style: row
      columns: 2
  - Applications:
      style: row
      columns: 3
  - Content:
      style: row
      columns: 1
  - Monitoring:
      style: row
      columns: 3
  - Automation:
      style: row
      columns: 1

# Appearance
headerStyle: clean
statusStyle: dot
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true

# Behavior
target: _blank
cardBlur: sm
hideVersion: false

# Language
language: en

# Show all docker container stats expanded
showStats: false
