name: vault

services:
  vaultwarden:
    image: ${DOCKER_IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME}_app
    restart: unless-stopped
    volumes:
      - ./bitwarden:/data:rw
    environment:
      TZ: ${TIMEZONE:-Europe/Amsterdam}
      ADMIN_TOKEN: ${JWT_TOKEN}
      WEBSOCKET_ENABLED: ${WEBSOCKET_ENABLED}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
      SMTP_HOST: ${EMAIL_SMTP_HOST}
      SMTP_FROM: ${EMAIL_FROM}
      SMTP_PORT: ${EMAIL_SMTP_PORT}
      # SMTP_SECURITY: ${SMTP_SECURITY}
      # SMTP_TIMEOUT: ${SMTP_TIMEOUT}
      SMTP_USERNAME: ${EMAIL_SMTP_USER}
      SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}
      DOMAIN: ${DOMAIN}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:$APP_PORT/alive || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - kompose_network
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.middlewares.$COMPOSE_PROJECT_NAME-redirect-web-secure.redirectscheme.scheme=https'
      - 'traefik.http.routers.$COMPOSE_PROJECT_NAME-web.middlewares=$COMPOSE_PROJECT_NAME-redirect-web-secure'
      - 'traefik.http.routers.$COMPOSE_PROJECT_NAME-web.rule=Host(`$TRAEFIK_HOST`)'
      - 'traefik.http.routers.$COMPOSE_PROJECT_NAME-web.entrypoints=web'
      - 'traefik.http.routers.$COMPOSE_PROJECT_NAME-web-secure.rule=Host(`$TRAEFIK_HOST`)'
      - 'traefik.http.routers.$COMPOSE_PROJECT_NAME-web-secure.tls.certresolver=resolver'
      - 'traefik.http.routers.$COMPOSE_PROJECT_NAME-web-secure.entrypoints=web-secure'
      - 'traefik.http.middlewares.$COMPOSE_PROJECT_NAME-web-secure-compress.compress=true'
      - 'traefik.http.routers.$COMPOSE_PROJECT_NAME-web-secure.middlewares=$COMPOSE_PROJECT_NAME-web-secure-compress'
      - 'traefik.http.services.$COMPOSE_PROJECT_NAME-web-secure.loadbalancer.server.port=$APP_PORT'
      - 'traefik.docker.network=kompose_network'

networks:
  kompose_network:
    name: ${NETWORK_NAME:-kompose}
    external: true
