/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
"use strict";
exports.countDbSize = require("./countDbSize.edge.js").countDbSize;
exports.countDistinctRecipients =
  require("./countDistinctRecipients.edge.js").countDistinctRecipients;
exports.countDistinctRecipientsInTimeRange =
  require("./countDistinctRecipientsInTimeRange.edge.js").countDistinctRecipientsInTimeRange;
exports.subscriberGrowthQuery =
  require("./subscriberGrowthQuery.edge.js").subscriberGrowthQuery;
