/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
"use strict";
const { makeTypedQueryFactory: $mkFactory } = require("../runtime/library");
exports.subscriberGrowthQuery = /*#__PURE__*/ $mkFactory(
  'SELECT\nDATE_TRUNC(\'day\', "createdAt") as date,\nCOUNT(*) as count\nFROM "public"."Subscriber"\nWHERE "organizationId" = $1\nAND "createdAt" >= $2\nAND "createdAt" <= $3\nGROUP BY DATE_TRUNC(\'day\', "createdAt")\nORDER BY date ASC',
);
